FROM apache/airflow:2.7.2

# Copy requirements
COPY docker/airflow/requirements.txt /requirements.txt

# Install airflow with constraints
RUN pip install --no-cache-dir -r /requirements.txt

# Copy DAGs and source code
COPY dags /opt/airflow/dags
COPY src /opt/airflow/src
